# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site

title: 东大门
subtitle: 折腾让世界更美好
description: 东大门博客专注于分享AI智能体项目实践、深度学习模型（如DDPG, YOLO）的训练与应用策略，以及硬件控制技术的最新进展。探索用AI技术革新海洋探鱼设备。
keywords: AI智能体, 深度学习, DDPG, YOLO, 强化学习, 探鱼设备, 硬件控制, 博客
author: 东大门
language: zh
timezone: ''

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://qtroni.web.app/
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
# skip_render: # 原本可能是这样
skip_render:
  - .well-known/**/* # 添加这一行，跳过渲染 .well-known 目录下的所有文件

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  # order_by: -date  # <-- 移除或注释掉按日期倒序
  order_by: -date  # <-- 新增：先按weight升序，再按日期倒序

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: cold-stone
# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  # 您的 Git 仓库地址 (使用 HTTPS 或 SSH 均可)
  # HTTPS 格式 (推荐，但可能需要输入密码/Token): 
  # https://github.com/dev-droid/my-hexo-blog.git
  # SSH 格式 (推荐使用 SSH Key):
  # git@github.com:dev-droid/my-hexo-blog.git
  repo: https://github.com/dev-droid/my-hexo-blog.git
  
  # 项目页面通常需要推送到 'gh-pages' 分支
  branch: gh-pages
  
  # 部署时的 Git 提交信息 (可选)
  message: "更新时间: {{ now('YYYY-MM-DD HH:mm:ss') }}"
# RSS Feed
feed:
  type: atom
  path: atom.xml
  limit: 20 # 限制在 RSS feed 中显示的文章数量，-1 表示所有文章
  hub:
  content:
  content_limit: 140
  content_limit_delim: ' '
  order_by: -date
  icon: avatar.png
  autodiscovery: true
# ---------------------------------------------------------------
# Hexo Search Plugin
# For hexo-generator-searchdb
# ---------------------------------------------------------------
search:
  path: search.xml
  field: post
  format: html
# ---------------------------------------------------------------
# For hexo-generator-sitemap
# ---------------------------------------------------------------
sitemap:
  path: 
    - sitemap.xml
    - sitemap.txt
  template: ./sitemap_template.xml
  template_txt: ./sitemap_template.txt
  rel: false
  tags: true
  categories: true

# 博客设置
seo_title: 东大门
project_dir: projects

# 用户设置
avatar: avatar.png

# Utteranc 评论系统
comment:
  repo: xrr2016/blog

# 社交平台链接：
#sns:
#  github: xrr2016
#  juejin: 576666b7207703006b1e0f09

# 博客访问数据
track:
  gaid: xxxxxxxxxxxxxx